name: build-spacy-termux

on:
  workflow_dispatch:   # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare wheels dir
        run: mkdir -p wheels

      - name: Build wheels inside Termux Docker
        run: |
          docker run --rm -v $PWD/wheels:/wheels termux/termux-docker:latest bash -lc '
            set -eux

            # Use a reliable mirror
            termux-change-repo -y || true

            # Update & upgrade
            pkg update -y || true
            pkg upgrade -y || true

            # Install build tools & libs
            pkg install -y python clang make cmake git binutils ninja pkg-config libffi openssl zlib libopenblas

            # Upgrade pip toolchain
            pip install -U pip setuptools wheel

            # Pre-build common heavy deps (optional)
            pip wheel --no-cache-dir --wheel-dir /wheels numpy || true
            pip wheel --no-cache-dir --wheel-dir /wheels pydantic_core pydantic || true
            pip wheel --no-cache-dir --wheel-dir /wheels blis cymem preshed murmurhash thinc srsly || true

            # Finally build spaCy
            pip wheel --no-cache-dir --wheel-dir /wheels spacy

            # Fix permissions for runner
            chown -R $(id -u):$(id -g) /wheels || true
          '

      - name: Pack wheels
        run: |
          tar czf spacy-termux-wheels.tar.gz -C wheels .
          mv spacy-termux-wheels.tar.gz wheels/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-termux-wheels
          path: wheels/spacy-termux-wheels.tar.gz
