name: build-android-wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare wheel output dir
        run: mkdir -p wheels

      - name: Build wheels inside Termux Docker
        run: |
          docker run --rm -v $PWD/wheels:/wheels termux/termux-docker:latest bash -c "
            pkg update -y &&
            pkg install -y python clang build-essential binutils &&
            pip install -U pip setuptools wheel &&
            pip wheel spacy --no-cache-dir --wheel-dir /wheels
          "

      - name: Pack wheels into tar.gz
        run: |
          cd wheels
          tar czf spacy-termux-aarch64.tar.gz *.whl
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-termux-aarch64
          path: wheels/spacy-termux-aarch64.tar.gz
