name: build-android-wheels

on:
  workflow_dispatch:   # run manually

jobs:
  termux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare wheels dir
        run: mkdir -p wheels

      - name: Build Termux-compatible wheels inside Termux Docker
        run: |
          docker run --rm -v $PWD/wheels:/wheels termux/termux-docker:latest bash -lc '
            set -ex

            # Update Termux packages
            pkg update -y || true
            pkg upgrade -y || true

            # Install essential build tools (ninja included so pip won’t compile its own)
            pkg install -y python clang make cmake git binutils ninja pkg-config libffi openssl zlib openblas

            # Upgrade pip and packaging tools
            pip install -U pip setuptools wheel

            # Build heavy deps first (optional)
            pip wheel --no-cache-dir --wheel-dir /wheels numpy || true
            pip wheel --no-cache-dir --wheel-dir /wheels pydantic_core pydantic || true
            pip wheel --no-cache-dir --wheel-dir /wheels blis cymem preshed murmurhash thinc srsly || true

            # Finally build spaCy
            pip wheel --no-cache-dir --wheel-dir /wheels spacy

            # Fix ownership for GitHub runner
            chown -R $(id -u):$(id -g) /wheels || true
          '

      - name: Pack artefact
        run: |
          tar czf spacy-termux-wheels.tar.gz -C wheels .
          mv spacy-termux-wheels.tar.gz wheels/

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-termux-wheels
          path: wheels/spacy-termux-wheels.tar.gz
