name: build-spacy-termux

on:
  workflow_dispatch:   # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare wheels dir
        run: mkdir -p wheels

      - name: Build wheels inside Termux Docker (ARM64)
        run: |
          docker run --rm --platform linux/arm64 \
            -v $PWD/wheels:/wheels \
            termux/termux-docker:latest bash -lc '
              set -eux
              pkg update && pkg upgrade -y
              pkg install -y python clang make cmake git binutils ninja pkg-config libffi openssl zlib libopenblas
              python -m pip install -U pip setuptools wheel
              export BLIS_ARCH=generic
              python -m pip wheel --no-cache-dir --wheel-dir /wheels numpy || true
              python -m pip wheel --no-cache-dir --wheel-dir /wheels pydantic_core pydantic || true
              python -m pip wheel --no-cache-dir --wheel-dir /wheels blis cymem preshed murmurhash thinc srsly || true
              python -m pip wheel --no-cache-dir --wheel-dir /wheels spacy
              chown -R $(id -u):$(id -g) /wheels || true
          '

      - name: Pack wheels
        run: |
          tar czf spacy-termux-wheels.tar.gz -C wheels .
          mv spacy-termux-wheels.tar.gz wheels/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-termux-wheels
          path: wheels/spacy-termux-wheels.tar.gz
