name: build-android-wheels

on:
  workflow_dispatch:   # manual button only

jobs:
  arm:
    runs-on: ubuntu-24.04-arm   # native ARM64 runner
    steps:
      - uses: actions/checkout@v4

      - name: Install system build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build wheels via Docker
        run: |
          docker run --rm -v $PWD/wheels:/wheels python:3.12-slim bash -c "
            apt-get update &&
            apt-get install -y build-essential &&
            pip install -U pip wheel &&
            export BLIS_ARCH=generic &&
            pip wheel spacy thinc blis cymem preshed murmurhash --wheel-dir /wheels"

      - name: Pack artefact
        run: |
          sudo chown -R $USER:$USER wheels   # fix any leftover root-owned files
          tar czf spacy-android-aarch64.tar.gz -C wheels .
          mv spacy-android-aarch64.tar.gz wheels/

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-android-aarch64
          path: wheels/spacy-android-aarch64.tar.gz
