name: build-android-wheels
on: workflow_dispatch
jobs:
  arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build wheels
        run: |
          docker run --rm -v $PWD/wheels:/wheels \
            --platform linux/arm64 python:3.12-slim bash -c "
              pip install -U pip wheel && \
              export BLIS_ARCH=generic && \
              pip wheel spacy thinc blis cymem preshed murmurhash --wheel-dir /wheels"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-android-aarch64
          path: wheels/*.whl
