name: build-spacy-android-arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install host tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Download Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r27-linux.zip
          unzip -q android-ndk-r27-linux.zip
          echo "$PWD/android-ndk-r27/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Build wheels for Android AArch64
        run: |
          mkdir wheels
          python -m pip install -U pip setuptools wheel
          # 1. build the heavy-deps first (they need BLIS_ARCH)
          python -m pip wheel --no-cache-dir --wheel-dir wheels numpy || true
          python -m pip wheel --no-cache-dir --wheel-dir wheels blis cymem preshed murmurhash thinc srsly || true
          python -m pip wheel --no-cache-dir --wheel-dir wheels pydantic_core pydantic || true
          # 2. build spaCy itself
          python -m pip wheel --no-cache-dir --wheel-dir wheels spacy

      - name: Pack artefacts
        run: |
          tar czf spacy-android-arm64-wheels.tar.gz -C wheels .
          mv spacy-android-arm64-wheels.tar.gz wheels/

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-android-arm64-wheels
          path: wheels/spacy-android-arm64-wheels.tar.gz
