name: build-android-wheels

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels for Android (Bionic)
        run: |
          docker run --rm -v $PWD/wheels:/wheels \
            ghcr.io/termux/termux-docker:aarch64 bash -c "
              apt-get update &&
              apt-get install -y clang python3-dev make &&
              python3 -m pip install -U pip wheel &&
              export BLIS_ARCH=generic &&
              python3 -m pip wheel spacy thinc blis cymem preshed murmurhash --wheel-dir /wheels"

      - name: Pack artefact
        run: |
          sudo chown -R $USER:$USER wheels
          tar czf spacy-android-aarch64.tar.gz -C wheels .

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: spacy-android-aarch64
          path: spacy-android-aarch64.tar.gz
